# put common definitions in here
CFLAGS    = -Wall  -DDEBUG -g
CC	  = gcc $(CFLAGS)
#PRJCFLAGS = -g
#LD	  = gcc
INC       = -I../lib
LDFLAGS   = 
#AR	  = ar
ARFLAGS	  =
#RANLIB	  = ranlib
RM	  = rm
ECHO	  = echo

SHELL	= /bin/sh

# .SILENT :
