# put common definitions in here
CFLAGS    = -Wall # -DDEBUG -g
CC	  = gcc
#PRJCFLAGS = -g
#LD	  = gcc
INC       += -I../lib
LDFLAGS   = 
LIBS      = -lpam
#AR	  = ar
ARFLAGS	  =
#RANLIB	  = ranlib
RM	  = rm
ECHO	  = echo

SHELL	= /bin/sh

SIBYL   = 1
# .SILENT :

